### ISSUE TITLE
CMakeLists.txt is missing?

### ISSUE THREAD

**Issue by WaterHyacinthInNANHU** [mic-rud/RABBIT-Transcoding#1]
Thank you for the code release! I encountered this error when running `./build.sh`.

Outputs:
```bash
./build.sh: line 8: cmake3: command not found
./build.sh: line 8: [: ==: unary operator expected
CMAKE      = cmake
MACHINE    = Linux
GENERATORS = Unix Makefiles
cmake -H. -B./build/Release -G Unix Makefiles   -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
CMake Error: The source directory "/home/user/Projects/RABBIT-Transcoding" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Build: /home/user/Projects/mingxuan/3d_vid/RABBIT-Transcoding 
make: *** build/Release: No such file or directory.  Stop.
```

My environment:
 - `Linux 5.15.0-91-generic #101~20.04.1-Ubuntu`
 - `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0`
 - `cmake version 3.26.1`

Please help~

**Comment by mic-rud** [comment]
Hi!
Thank you for your interest in our work!

I excluded the file during clean-up by mistake, this should now be fixed.

Let me know if you run into any other issues.

**Comment by WaterHyacinthInNANHU** [comment]
> Hi! Thank you for your interest in our work!
> 
> I excluded the file during clean-up by mistake, this should now be fixed.
> 
> Let me know if you run into any other issues.

Thanks! It works now.
